apiVersion: v1
kind: Service
metadata:
  name: vercel-frontend-service
spec:
  selector:
    app: fully-local-pdf-chatbot
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
